# Generated by Django 6.1.1 on 2026-09-23 20:03

import apps.orders.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order_number', models.CharField(db_index=True, default=apps.orders.models.generate_order_number, max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('total_amount_yer', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ الإجمالي (YER)')),
                ('currency_used', models.CharField(default='YER', max_length=10, verbose_name='العملة المستخدمة')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار ⏳'), ('PROCESSING', 'جاري المعالجة والتسليم ⚙️'), ('COMPLETED', 'مكتمل بنجاح ✅'), ('FAILED', 'فشل التنفيذ ⚠️'), ('CANCELLED', 'ملغي 🚫'), ('REFUNDED', 'مسترجع بالكامل 🔄')], db_index=True, default='PENDING', max_length=20, verbose_name='حالة الطلب')),
                ('customer_input_data', models.TextField(blank=True, verbose_name='بيانات مدخلة من العميل (ID/حساب)')),
                ('delivered_data', models.TextField(blank=True, verbose_name='البيانات المسلمة للعميل')),
                ('failure_reason', models.TextField(blank=True, verbose_name='سبب الفشل إن وجد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.telegramprofile', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب شراء',
                'verbose_name_plural': 'طلبات الشراء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='اسم المنتج وقت الشراء')),
                ('unit_price_snapshot_yer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة وقت الشراء (YER)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('total_price_yer', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الإجمالي بالريال اليمني')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلبات',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('from_status', models.CharField(max_length=20, verbose_name='الحالة السابقة')),
                ('to_status', models.CharField(max_length=20, verbose_name='الحالة الجديدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات التغيير')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تاريخ حالة الطلب',
                'verbose_name_plural': 'سجل حالات الطلب',
                'ordering': ['created_at'],
            },
        ),
    ]
