# Generated by Django 6.1.1 on 2026-09-23 20:03

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='مفتاح الإعداد')),
                ('value', models.TextField(verbose_name='القيمة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'إعداد نظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('source_currency', models.CharField(default='USD', max_length=10, verbose_name='العملة المصدر')),
                ('target_currency', models.CharField(default='YER', max_length=10, verbose_name='العملة الهدف')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('550.0000'), max_digits=12, verbose_name='سعر الصرف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'سعر صرف',
                'verbose_name_plural': 'أسعار الصرف',
                'unique_together': {('source_currency', 'target_currency')},
            },
        ),
    ]
