# Generated by Django 6.1.1 on 2026-09-23 20:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=150, verbose_name='اسم طريقة الدفع')),
                ('icon', models.CharField(default='💳', max_length=20, verbose_name='أيقونة الطريقة')),
                ('account_number', models.CharField(max_length=100, verbose_name='رقم الحساب أو النقطة')),
                ('account_name', models.CharField(blank=True, max_length=150, verbose_name='اسم صاحب الحساب')),
                ('instructions', models.TextField(verbose_name='تعليمات التحويل للعميل')),
                ('requires_proof_image', models.BooleanField(default=True, verbose_name='تتطلب صورة إشعار التحويل')),
                ('requires_tx_number', models.BooleanField(default=True, verbose_name='تتطلب رقم الحوالة / السند')),
                ('min_deposit_yer', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=12, verbose_name='الحد الأدنى (YER)')),
                ('max_deposit_yer', models.DecimalField(decimal_places=2, default=Decimal('500000'), max_digits=12, verbose_name='الحد الأقصى (YER)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('amount_yer', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المحول (YER)')),
                ('tx_number', models.CharField(blank=True, max_length=150, verbose_name='رقم الحوالة / العملية')),
                ('proof_image_file_id', models.CharField(blank=True, max_length=255, verbose_name='معرف صورة الإشعار في تليجرام')),
                ('proof_image_url', models.URLField(blank=True, verbose_name='رابط صورة الإشعار')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة ⏳'), ('APPROVED', 'تم القبول والاعتماد ✅'), ('REJECTED', 'تم الرفض ❌')], db_index=True, default='PENDING', max_length=20, verbose_name='حالة الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('admin_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='معرف رسالة مجموعة الإدارة')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='payments.paymentmethod', verbose_name='طريقة الدفع')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to='users.telegramprofile', verbose_name='تمت المراجعة بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='users.telegramprofile', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب شحن رصيد',
                'verbose_name_plural': 'طلبات شحن الرصيد',
                'ordering': ['-created_at'],
            },
        ),
    ]
