# Generated by Django 6.1.1 on 2026-09-23 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('codename', models.CharField(choices=[('MANAGE_PRODUCTS', 'إدارة المنتجات'), ('MANAGE_CATEGORIES', 'إدارة التصنيفات'), ('MANAGE_INVENTORY', 'إدارة المخزون'), ('MANAGE_ORDERS', 'إدارة الطلبات'), ('MANAGE_PAYMENTS', 'إدارة ومراجعة المدفوعات'), ('MANAGE_USERS', 'إدارة المستخدمين'), ('MANAGE_SERVICES', 'إدارة الخدمات الرقمية'), ('MANAGE_PROVIDERS', 'إدارة المزودين'), ('MANAGE_ADMINS', 'إدارة المشرفين'), ('MANAGE_SETTINGS', 'إدارة الإعدادات والعملات'), ('VIEW_AUDIT_LOGS', 'عرض سجلات التدقيق')], max_length=50, unique=True, verbose_name='كود الصلاحية')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف الصلاحية')),
            ],
            options={
                'verbose_name': 'صلاحية إدارية',
                'verbose_name_plural': 'الصلاحيات الإدارية',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='معرف التليجرام')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المستخدم')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='الاسم الأخير')),
                ('preferred_currency', models.CharField(choices=[('YER', 'ريال يمني (YER)'), ('USD', 'دولار أمريكي (USD)')], default='YER', max_length=10, verbose_name='العملة المفضلة')),
                ('is_banned', models.BooleanField(default=False, verbose_name='محظور')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مشرف')),
            ],
            options={
                'verbose_name': 'مستخدم تليجرام',
                'verbose_name_plural': 'مستخدمو تليجرام',
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('permissions', models.ManyToManyField(blank=True, to='users.adminpermission', verbose_name='الصلاحيات')),
            ],
            options={
                'verbose_name': 'دور إداري',
                'verbose_name_plural': 'الأدوار الإدارية',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='مشرف عام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('custom_permissions', models.ManyToManyField(blank=True, to='users.adminpermission', verbose_name='صلاحيات إضافية')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminrole', verbose_name='الدور')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_details', to='users.telegramprofile', verbose_name='الملف الشخصي')),
            ],
            options={
                'verbose_name': 'مشرف نظام',
                'verbose_name_plural': 'مشرفو النظام',
            },
        ),
    ]
