# Generated by Django 6.1.1 on 2026-09-23 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المزود')),
                ('provider_code', models.CharField(max_length=50, unique=True, verbose_name='رمز المزود التعريفي')),
                ('provider_type', models.CharField(choices=[('MOCK', 'مزود تجريبي ومحاكي (Mock / Simulator)'), ('CUSTOM_HTTP', 'مزود API خارجي حقيقي')], default='MOCK', max_length=20, verbose_name='نوع المزود')),
                ('base_url', models.URLField(blank=True, verbose_name='رابط الـ API الأساسي')),
                ('api_key_encrypted', models.TextField(blank=True, verbose_name='مفتاح الـ API المشفر')),
                ('api_secret_encrypted', models.TextField(blank=True, verbose_name='كلمة السر أو Secret المشفرة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مزود خارجي',
                'verbose_name_plural': 'المزودون الخارجيون',
            },
        ),
        migrations.CreateModel(
            name='ProviderProductMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('external_service_id', models.CharField(max_length=150, verbose_name='معرف الخدمة لدى المزود')),
                ('custom_parameters', models.JSONField(blank=True, default=dict, verbose_name='معاملات إضافية (JSON)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_mapping', to='catalog.product', verbose_name='المنتج المحلي')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='providers.apiprovider', verbose_name='المزود الخارجي')),
            ],
            options={
                'verbose_name': 'ربط منتج بمزود',
                'verbose_name_plural': 'روابط المنتجات بالمزودين',
            },
        ),
    ]
