# Generated by Django 6.1.1 on 2026-09-23 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('encrypted_data', models.TextField(verbose_name='البيانات المشفرة (حساب/كود/مفتاح)')),
                ('item_identifier', models.CharField(blank=True, max_length=100, verbose_name='معرف أو رقم العنصر')),
                ('status', models.CharField(choices=[('AVAILABLE', 'متاح للبيع'), ('RESERVED', 'محجوز لطلب قيد المعالجة'), ('SOLD', 'تم بيعه وتسليمه'), ('DISABLED', 'معطل / غير صالح')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='حالة العنصر')),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='معرف الطلب المرتبط')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البيع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر مخزون رقمي',
                'verbose_name_plural': 'عناصر المخزون الرقمي',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestockSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_notified', models.BooleanField(default=False, verbose_name='تم إرسال الإشعار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_subscribers', to='catalog.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_alerts', to='users.telegramprofile', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اشتراك إشعار توفر المخزون',
                'verbose_name_plural': 'اشتراكات إشعارات توفر المخزون',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
