# Generated by Django 6.1.1 on 2026-09-23 20:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة وتفاصيلها')),
                ('service_type', models.CharField(choices=[('FIXED', 'خدمة بسعر محدد وثابت'), ('CUSTOM', 'خدمة مخصصة تتطلب تسعير من الإدارة (Quote)')], default='FIXED', max_length=20, verbose_name='نوع الخدمة')),
                ('price_yer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='السعر الثابت (YER)')),
                ('instructions', models.TextField(blank=True, verbose_name='البيانات والمرفقات المطلوبة من العميل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'خدمة رقمية',
                'verbose_name_plural': 'الخدمات الرقمية',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer_notes', models.TextField(verbose_name='ملاحظات وتفاصيل طلب العميل')),
                ('attachment_file_id', models.CharField(blank=True, max_length=255, verbose_name='معرف المرفق في تليجرام')),
                ('attachment_url', models.URLField(blank=True, verbose_name='رابط المرفق السحابي')),
                ('status', models.CharField(choices=[('PENDING_QUOTE', 'بانتظار تسعير الإدارة ⏳'), ('QUOTE_PROVIDED', 'تم تقديم عرض السعر للعميل 💼'), ('ACCEPTED', 'تم قبول العرض والخصم بنجاح ✅'), ('REJECTED', 'تم رفض العرض أو إلغاء الطلب ❌'), ('COMPLETED', 'تم إنجاز وتسليم الخدمة 🎯')], db_index=True, default='PENDING_QUOTE', max_length=20, verbose_name='حالة الطلب')),
                ('quote_amount_yer', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='سعر العرض المقدم (YER)')),
                ('quote_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء صلاحية العرض')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات المشرف')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_source', to='orders.order', verbose_name='الطلب المنشأ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='services_app.digitalservice', verbose_name='الخدمة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='users.telegramprofile', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب خدمة',
                'verbose_name_plural': 'طلبات الخدمات',
                'ordering': ['-created_at'],
            },
        ),
    ]
