# Generated by Django 6.1.1 on 2026-09-23 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('status', models.CharField(choices=[('QUEUED', 'في الانتظار ⏳'), ('RUNNING', 'جاري التنفيذ ⚙️'), ('SUCCESS', 'تم بنجاح ✅'), ('FAILED', 'فشل نهائي ❌')], db_index=True, default='QUEUED', max_length=20, verbose_name='حالة المهمة')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='الحد الأقصى للمحاولات')),
                ('last_error', models.TextField(blank=True, verbose_name='آخر خطأ مسجل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_tasks', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مهمة تسليم',
                'verbose_name_plural': 'مهام التسليم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('issue_type', models.CharField(default='API_DELIVERY_FAILURE', max_length=50, verbose_name='نوع المشكلة')),
                ('details', models.TextField(verbose_name='تفاصيل المشكلة والخطأ')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='تم الحل')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='orders.order', verbose_name='الطلب')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to='users.telegramprofile', verbose_name='تم الحل بواسطة')),
            ],
            options={
                'verbose_name': 'مشكلة طلب',
                'verbose_name_plural': 'مشاكل الطلبات',
                'ordering': ['-created_at'],
            },
        ),
    ]
