# Generated by Django 6.1.1 on 2026-09-23 20:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('balance_yer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد بالريال اليمني')),
                ('is_locked', models.BooleanField(default=False, verbose_name='محفظة مقفلة / مجمدة')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.telegramprofile', verbose_name='الملف الشخصي')),
            ],
            options={
                'verbose_name': 'محفظة',
                'verbose_name_plural': 'المحافظ',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('tx_type', models.CharField(choices=[('DEPOSIT', 'إيداع رصيد'), ('PURCHASE', 'شراء منتج أو خدمة'), ('REFUND', 'استرجاع مالي'), ('ADJUSTMENT', 'تعديل إداري')], db_index=True, max_length=20, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الرصيد قبل')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الرصيد بعد')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='الرقم المرجعي للعملية')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True, verbose_name='مفتاح منع التكرار')),
                ('description', models.TextField(blank=True, verbose_name='وصف العملية')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'حركة مالية',
                'verbose_name_plural': 'الحركات المالية',
                'ordering': ['-created_at'],
            },
        ),
    ]
