# Generated by Django 6.1.1 on 2026-09-23 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='العملية')),
                ('resource_type', models.CharField(db_index=True, max_length=50, verbose_name='نوع العنصر')),
                ('resource_id', models.CharField(db_index=True, max_length=100, verbose_name='معرف العنصر')),
                ('before_state', models.JSONField(blank=True, default=dict, verbose_name='الحالة قبل التعديل')),
                ('after_state', models.JSONField(blank=True, default=dict, verbose_name='الحالة بعد التعديل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.telegramprofile', verbose_name='المشرف المنفذ')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-created_at'],
            },
        ),
    ]
