# Generated by Django 6.1.1 on 2026-09-23 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=150, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='الاسم اللطيف (Slug)')),
                ('icon', models.CharField(default='📁', max_length=20, verbose_name='أيقونة التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, verbose_name='وصف المنتج')),
                ('base_currency', models.CharField(choices=[('YER', 'ريال يمني (YER)'), ('USD', 'دولار أمريكي (USD)')], default='YER', max_length=10, verbose_name='عملة التسعير الأساسية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الأساسي')),
                ('stock_type', models.CharField(choices=[('QUANTITY', 'كمية عددية (Numeric Stock)'), ('INDIVIDUAL_ITEMS', 'عناصر وحسابات فردية مستقلة'), ('API_CAPACITY', 'مرتبط بمزود خارجي (External API)'), ('UNLIMITED', 'غير محدود (Unlimited)')], default='QUANTITY', max_length=20, verbose_name='نوع المخزون')),
                ('fulfillment_type', models.CharField(choices=[('INVENTORY', 'تسليم فوري من المخزون الداخلي'), ('API', 'شراء تلقائي عبر API المزود الخارجي'), ('FILE', 'تسليم ملف رقمي'), ('MANUAL', 'تنفيذ يدوي من قبل الإدارة')], default='INVENTORY', max_length=20, verbose_name='نوع التسليم')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة (للمخزون العددي)')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='حد تنبيه نفاد المخزون')),
                ('requires_customer_input', models.BooleanField(default=False, verbose_name='يتطلب بيانات إضافية من العميل (مثل ID اللاعب أو الإيميل)')),
                ('customer_input_label', models.CharField(blank=True, max_length=150, verbose_name='عنوان الحقل المطلوب من العميل')),
                ('image_url', models.URLField(blank=True, verbose_name='رابط الصورة (Cloudinary)')),
                ('image_public_id', models.CharField(blank=True, max_length=150, verbose_name='معرف Cloudinary للصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل للبيع')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('categories', models.ManyToManyField(related_name='products', to='catalog.category', verbose_name='التصنيفات')),
            ],
            options={
                'verbose_name': 'منتج رقمي',
                'verbose_name_plural': 'المنتجات الرقمية',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('image_url', models.URLField(verbose_name='رابط الصورة')),
                ('public_id', models.CharField(max_length=150, verbose_name='معرف الصورة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
            },
        ),
    ]
