# Generated by Django 6.1.1 on 2026-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='معرف الصورة الخارجي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='رابط صورة المنتج'),
        ),
    ]
