# Generated by Django 6.1.1 on 2026-09-23 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('message_text', models.TextField(verbose_name='نص الرسالة')),
                ('target_count', models.PositiveIntegerField(default=0, verbose_name='المستهدفون')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='تم الإرسال بنجاح')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='فشل الإرسال')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
            ],
            options={
                'verbose_name': 'رسالة بث جماعي',
                'verbose_name_plural': 'رسائل البث الجماعي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('channel_id', models.CharField(max_length=120, unique=True, verbose_name='معرف القناة أو اليوزر (مثال: @Channel أو -100...)')),
                ('channel_title', models.CharField(max_length=150, verbose_name='اسم القناة')),
                ('invite_link', models.URLField(verbose_name='رابط الدعوة للقناة')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='إجباري للدخول')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'قناة اشتراك إجباري',
                'verbose_name_plural': 'قنوات الاشتراك الإجباري',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
